{%set name = "fbprophet" %}
{%set version = "0.1.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "5be931cf0f2c73eb221b269241bb15be0860497511026fd34a7e4da76395f20e" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [win and py27]
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]
  binary_has_prefix_files:
    - Lib/site-packages/fbprophet/stan_models/linear_growth.pkl            # [win]
    - Lib/site-packages/fbprophet/stan_models/logistic_growth.pkl          # [win]
    - lib/python*/site-packages/fbprophet/stan_models/linear_growth.pkl    # [unix]
    - lib/python*/site-packages/fbprophet/stan_models/logistic_growth.pkl  # [unix]

requirements:
  build:
    - toolchain  # [unix]
    - python
    - setuptools
    - cython >=0.22
    - pystan >=2.14
    # Pystan models depend on numpy and as they are compiled and pickled we
    # need to pin numpy version.
    - numpy x.x

  run:
    - python
    # setuptools is required for pkg_resources
    - setuptools
    - cython >=0.22
    - pystan >=2.14
    - numpy x.x
    - pandas >=0.18.1
    - matplotlib

test:
  requires:
    - pytest

  commands:
    - py.test -v --pyargs fbprophet

about:
  home: https://facebookincubator.github.io/prophet/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Automatic Forecasting Procedure'
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly and weekly
    seasonality, plus holidays. It works best with daily periodicity data with
    at least one year of historical data. Prophet is robust to missing data,
    shifts in the trend, and large outliers.
  doc_url: https://facebookincubator.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebookincubator/prophet

extra:
  recipe-maintainers:
    - pmlandwehr
    - rolando
