travis:
  secure:
    BINSTAR_TOKEN: CRCiT4p58iZS8s9hZIzjrfrNqjUlDmmw2BCXfPd9yvuzw7K9dgEbONuXus8yAwtQkmJFQnvYQfBJUpeud7rzRHcRuau9LxNSJhGa8MkjjjSluSMGHX6vL3MqumcQFsTx8JIAWJY5a1raPx/umrW2PnkQWX/l8BBvbHxXYAUnecX8B6o5yJB6Fk63ruShI4C8A9yI3bo3hUw4Rklou2X6gVoEUAgNyNdseN+sdya0+HGq8ahqMVXL4RUhsyiXiE8elpq574D7brOlJ77cA33wnn57UVo9HF26vUHmyCAFq3Q2SC5i45K+6S8X1PQEntgYEzPhQBg4cGOPE1AIK2wYd3DyBFnRLrnNTkHQ9tgYlawWvmdxaehwJCs+NaCCvLnVS69/RXW1WYzy35n30fYi6TaPkyL2C138LhRRF+aZco1ZFa7EiXHkcMOf32qtIRNRPCCjjt0PEwwnrCxi7UZCcXLcGb+YjkN7Xt3bHUurBgnC+YRtCg5JMpEgVpoWRQzZ5UYNNMh8FJZkG8m7a38OLSW1QP1h8OAWmNtsNkabASc6VW4Gmr6e8/hZW+7s34EsGBsdI6T0kvQ+JIzgUttSgpqdckKOUIzwCeNjFsesxJZbR9Nuhnegt8BYGINpkW8zMQAHBx/l9gboyuYzXdyLkL9/QNA4g++obFl6SSWQOUw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
