travis:
  secure:
    BINSTAR_TOKEN: TY2ekWWB7zyRLz0bfQ5NISTaIgkfB0xtvlewWAa8JfatZkSQyHGgU1Nl8gyIxZkNSklVy9Dv3sOrBMbeVU+7luufc0OKBQOgqkJfenCk88ySyTzFzpX9O8jNnVkseL4xiWjcPCvJ0aQk/jD7iqttalbFuw9V8YjD5sbI0rps8TWnbIZ+Wna3fmSVvXuahTEJCqMhpZRvlZDfxqO21aF6Fqlnur+DvCjGP0nFgngK/OkwNlyEmqwSQpldL3l/SUz6aVmMSDHA1Za9ljlAXmCnTYdWYCKi1dc2LtFpnU93Bc1qJR9IDIBHVXvbjkNiqUBVAvVNcun8dGmMcnD7sjw29LHjxvfkKyGIW2PJfgCxZi1ff2htTRCF/gIjIaLeuwr6aEC+Ss37t7WHZhfCQZkwpcbs8gA84N/yq2i6RoCQLBsDwtMDcZRaa5Wdqb0qF9y965JmnTRjFVTaorBz9tmWGOi0NITmy47BvSdlm6Xkuqmcxbim73V1Y4KKamV6JqId9JUAxFeLAKpcxX29L3QjoJY0grUxDWqQDI6kqwS/ph9LDPWnOEO2Ch4VfwHnmvZplnKOGsS+Zp20SBKRDmFsbFt3Ed/SLOQHxLK5OCcQndUe5oqbcX6fr0gNxHivZgx+1MrIrokJVr0TCS0+fknLJJQx5ibV//YZ6XdiIwByGvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
